# Generated by Django 5.1.6 on 2025-02-26 14:12

import crm.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО Клиента')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('phone_2', models.CharField(blank=True, max_length=12, verbose_name='Второй телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=12, verbose_name='Whatsapp')),
                ('telegram', models.CharField(blank=True, max_length=55, verbose_name='telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('service_name', models.CharField(max_length=155, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Подробное описание заявки')),
                ('cost_price', models.IntegerField(verbose_name='Общая себестоимость')),
                ('total_price', models.PositiveIntegerField(verbose_name='Общая стоимость')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='ImageForServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=crm.utils.service_request_file_path, verbose_name='Изображение к заявке')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crm.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.servicerequest', verbose_name='Заявка')),
            ],
        ),
    ]
