# Generated by Django 5.1.6 on 2025-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_client_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='cost_price',
            field=models.IntegerField(blank=True, verbose_name='Общая себестоимость'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Общая стоимость'),
        ),
    ]
