# Generated by Django 5.1.6 on 2025-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_client_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='cost_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая себестоимость'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Общая стоимость'),
        ),
    ]
