# Generated by Django 5.1.6 on 2025-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_servicerequest_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('canceled', 'Отменена'), ('archive', 'В архиве')], default='new', max_length=15),
        ),
    ]
