# Generated by Django 5.1.6 on 2025-03-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_servicerequest_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coastpricecase',
            name='sum',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общая себестоимость кейса'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='cost_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общая себестоимость'),
        ),
    ]
