# Generated by Django 5.1.6 on 2025-03-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_coastpricecase_sum_alter_servicerequest_cost_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoastPriceCase',
            new_name='CostPriceCase',
        ),
    ]
