# Generated by Django 5.1.6 on 2025-03-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_rename_coastpricecase_costpricecase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partofcoatpricecase',
            old_name='coast_price_case',
            new_name='cost_price_case',
        ),
    ]
