# Generated by Django 5.1.6 on 2025-03-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_rename_coast_price_case_partofcoatpricecase_cost_price_case'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartOfCoatPriceCase',
            new_name='PartOfCostPriceCase',
        ),
    ]
