# Generated by Django 5.1.6 on 2025-03-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_rename_partofcoatpricecase_partofcostpricecase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Общая стоимость'),
        ),
    ]
