# Generated by Django 5.1.6 on 2025-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_servicerequest_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='costpricecase',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Актуальный'),
        ),
    ]
