# Generated by Django 5.1.6 on 2025-03-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_costpricecase_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costpricecase',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Актуальный'),
        ),
    ]
