# Generated by Django 5.1.6 on 2025-03-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_costpricecase_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteforservicerequest',
            name='be_completed_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
