# Generated by Django 5.1.6 on 2025-03-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_noteforservicerequest_be_completed_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteforservicerequest',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Просрочена'),
        ),
        migrations.AlterField(
            model_name='noteforservicerequest',
            name='be_completed_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выполнить до'),
        ),
    ]
