# Generated by Django 5.1.6 on 2025-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_noteforservicerequest_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteforservicerequest',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
        migrations.AddField(
            model_name='noteforservicerequest',
            name='reminder',
            field=models.BooleanField(default=False, verbose_name='Напоминание'),
        ),
    ]
