# Generated by Django 5.1.6 on 2025-03-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_noteforservicerequest_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteforservicerequest',
            name='be_completed_before',
        ),
        migrations.RemoveField(
            model_name='noteforservicerequest',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='noteforservicerequest',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='noteforservicerequest',
            name='reminder',
        ),
        migrations.AddField(
            model_name='task',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Просрочена'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.BooleanField(default=False, verbose_name='Напоминание'),
        ),
    ]
