# Generated by Django 5.1.6 on 2025-03-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_alter_task_options_alter_servicerequest_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder',
        ),
    ]
