# Generated by Django 5.1.6 on 2025-03-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_alter_client_options_remove_task_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notifications',
            field=models.BooleanField(default=False, verbose_name='Оповещение'),
        ),
    ]
