# Generated by Django 5.1.6 on 2025-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_task_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='before_one_hour_deadline_notification',
            field=models.BooleanField(default=False, verbose_name='Оповещение за час о просрочке задачи'),
        ),
    ]
