# Generated by Django 5.1.6 on 2025-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_task_before_one_hour_deadline_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='before_one_workday_deadline_notification',
            field=models.BooleanField(default=False, verbose_name='Оповещение за рабочий день до дедлайна было отправлено'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='day_off_notification',
            field=models.BooleanField(default=False, verbose_name='Оповещения по выходным'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notification',
            field=models.BooleanField(default=True, verbose_name='Оповещения на почту'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notification',
            field=models.BooleanField(default=True, verbose_name='Оповещения в телеграм'),
        ),
        migrations.AlterField(
            model_name='task',
            name='before_one_hour_deadline_notification',
            field=models.BooleanField(default=False, verbose_name='Оповещение за час о просрочке задачи было отправлено'),
        ),
    ]
