# Generated by Django 5.1.6 on 2025-03-20 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_task_before_one_workday_deadline_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='must_be_completed_by',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Должна быть выполнена до'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('custom', 'Кастомное')], max_length=10)),
                ('custom_days', models.JSONField(blank=True, help_text="Выбранные дни недели для кастомных напоминаний (например, ['mon', 'wed', 'fri'])", null=True, verbose_name='Кастомные дни недели')),
                ('custom_time', models.TimeField(blank=True, help_text='Время для кастомных напоминаний', null=True, verbose_name='Кастомное время напоминания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последнее отправленное напоминание')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.task', verbose_name='Задача')),
            ],
        ),
    ]
