# Generated by Django 5.1.6 on 2025-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_alter_task_must_be_completed_by_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='must_be_completed_by',
            field=models.DateTimeField(verbose_name='Должна быть выполнена до'),
        ),
    ]
