# Generated by Django 5.1.6 on 2025-04-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_displaynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaynotification',
            name='link_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='displaynotification',
            name='link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='displaynotification',
            name='type',
            field=models.CharField(choices=[('one_hour_before_task_expired', 'За час до просрочки задачи'), ('one_workday_before_task_expired', 'За день до просрочки задачи'), ('on_task_expired', 'В момент просрочки задачи'), ('reminder', 'Напоминание')], max_length=35),
        ),
    ]
