# Generated by Django 5.1.6 on 2025-04-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_displaynotification_link_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['must_be_completed_by', '-expired', 'is_completed'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
