# Generated by Django 5.1.6 on 2025-04-10 09:15

import crm.models
import crm.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_alter_servicerequest_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', '-expired', 'must_be_completed_by'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.CreateModel(
            name='FileForServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=crm.utils.service_request_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'doc', 'docx', 'xls', 'xlsx']), crm.models.validate_file_size], verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('document', 'Документ')], max_length=10)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.servicerequest')),
            ],
            options={
                'verbose_name': 'Файл для заявки',
                'verbose_name_plural': 'Файлы для заявок',
            },
        ),
        migrations.DeleteModel(
            name='ImageForServiceRequest',
        ),
    ]
