# Generated by Django 5.1.6 on 2025-04-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_alter_task_options_fileforservicerequest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileForServiceRequest',
        ),
    ]
