# Generated by Django 5.1.6 on 2025-04-14 09:07

import crm.models
import crm.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_delete_fileforservicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=crm.utils.service_request_file_path, validators=[crm.models.validate_file_size])),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crm.servicerequest')),
            ],
        ),
    ]
