# Generated by Django 5.1.6 on 2025-04-14 09:55

import crm.models
import crm.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_servicerequestimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=crm.utils.service_request_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'xls', 'xlsx', 'ods', 'pdf']), crm.models.validate_file_size], verbose_name='Документ')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.servicerequest')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
