# Generated by Django 5.1.6 on 2025-04-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_servicerequestdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='telegram'),
        ),
    ]
