# Generated by Django 5.1.6 on 2025-04-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_alter_userprofile_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, unique=True, verbose_name='telegram'),
        ),
    ]
