# Generated by Django 5.1.6 on 2025-05-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_2',
            field=models.CharField(blank=True, max_length=16, verbose_name='Второй телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='телефон'),
        ),
    ]
