# Generated by Django 5.1.6 on 2025-05-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_alter_client_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costpricecase',
            options={'ordering': ['sum'], 'verbose_name': 'Кейс себестоимости', 'verbose_name_plural': 'Кейс себестоимости'},
        ),
    ]
